openapi: 3.0.0
info:
  title: Bookstore - OpenAPI 3.1.0
  description: microservice and api development exercise
  version: 1.0.0
servers:
  - url: localhost:8000
tags:
  - name: book
    description: all operations related to books.
paths:
  /book:
    post:
      tags:
        - book
      summary: Create a new book
      description: This path will create a new book
      operationId: createNewBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /books:
    get:
      tags:
        - book
      summary: Retrieve all books
      description: This path returns all available books
      operationId: returnBooks
      parameters:
        - name: author
          in: query
          description: Return books by author name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Books'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /book/{book_id}:
    get:
      tags:
        - book
      summary: Retrieve a book by ID
      description: This operation retrieves a book by its ID
      operationId: getBookById
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - book
      summary: Update a book
      description: Update a book by its ID
      operationId: updateBook
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - book
      summary: Delete a book
      description: This operation deletes a book by its ID
      operationId: deleteBook
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 50
        author:
          type: string
          maxLength: 50
        isbn:
          type: string
          minLength: 13
          maxLength: 13
        rating:
          type: number
          minimum: 0
          maximum: 5
        publish_date:
          type: string
          format: date-time
        created_date:
          type: string
          format: date-time
          readOnly: true
        modified_date:
          type: string
          format: date-time
          readOnly: true
        location:
          type: string
          maxLength: 100
        access:
          type: string
          enum: [public, private, restricted]
          description: Access level of the book
      required:
        - name
        - author
        - isbn
        - rating
        - publish_date
    Books:
      type: array
      items:
        $ref: '#/components/schemas/Book'
    Success:
      type: object
      properties:
        message:
          type: string
          example: 'Book successfully created'
        id:
          type: string
          example: '123'
    Error:
      type: object
      properties:
        message:
          type: string
          example: 'Sorry something goes wrong, try again!'